# Generated by Django 5.0.7 on 2024-09-10 19:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="empbasicinfo",
            fields=[
                ("emp_name", models.CharField(max_length=255)),
                (
                    "father_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[("Male", "Male"), ("Female", "Female")],
                        max_length=6,
                        null=True,
                    ),
                ),
                (
                    "cnic",
                    models.CharField(
                        max_length=16, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("designation", models.CharField(max_length=255)),
                ("bps", models.CharField(blank=True, max_length=2, null=True)),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                ("date_of_joining", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "empbasicinfo",
            },
        ),
        migrations.CreateModel(
            name="empsalary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sal_month", models.CharField(max_length=25)),
                ("sal_year", models.CharField(max_length=4)),
                ("bank_name", models.CharField(blank=True, max_length=255, null=True)),
                ("ntn", models.CharField(blank=True, max_length=50, null=True)),
                ("account_no", models.CharField(blank=True, max_length=125, null=True)),
                ("basic_sal", models.IntegerField(max_length=10)),
                (
                    "med_allowance",
                    models.IntegerField(blank=True, max_length=12, null=True),
                ),
                (
                    "convence_allowance",
                    models.IntegerField(blank=True, max_length=12, null=True),
                ),
                (
                    "house_rent",
                    models.IntegerField(blank=True, max_length=12, null=True),
                ),
                ("dra_2015", models.IntegerField(blank=True, max_length=12, null=True)),
                ("ara_2022", models.IntegerField(blank=True, max_length=12, null=True)),
                ("ara_2023", models.IntegerField(blank=True, max_length=12, null=True)),
                ("ara_2014", models.IntegerField(blank=True, max_length=12, null=True)),
                (
                    "special_allowance",
                    models.IntegerField(blank=True, max_length=12, null=True),
                ),
                (
                    "utility_allowance",
                    models.IntegerField(blank=True, max_length=12, null=True),
                ),
                ("totall", models.IntegerField(blank=True, max_length=12, null=True)),
                (
                    "provident_fund_emp",
                    models.IntegerField(blank=True, max_length=12, null=True),
                ),
                (
                    "provident_fund_bef",
                    models.IntegerField(blank=True, max_length=12, null=True),
                ),
                (
                    "provident_fund_balance",
                    models.IntegerField(blank=True, max_length=12, null=True),
                ),
                ("pfcm", models.IntegerField(blank=True, max_length=12, null=True)),
                ("cpfb", models.IntegerField(blank=True, max_length=12, null=True)),
                ("wdpf", models.IntegerField(blank=True, max_length=12, null=True)),
                ("profit", models.IntegerField(blank=True, max_length=12, null=True)),
                ("apfb", models.IntegerField(blank=True, max_length=12, null=True)),
                ("eobi_emp", models.IntegerField(blank=True, max_length=12, null=True)),
                ("eobi_bef", models.IntegerField(blank=True, max_length=12, null=True)),
                ("atp", models.IntegerField(blank=True, max_length=12, null=True)),
                (
                    "income_tax",
                    models.IntegerField(blank=True, max_length=12, null=True),
                ),
                (
                    "total_deduction",
                    models.IntegerField(blank=True, max_length=12, null=True),
                ),
                (
                    "net_salary",
                    models.IntegerField(blank=True, max_length=12, null=True),
                ),
                (
                    "adhoc_allowance",
                    models.IntegerField(blank=True, max_length=12, null=True),
                ),
                (
                    "group_insurance",
                    models.IntegerField(blank=True, max_length=12, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "cnic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="employees.empbasicinfo",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "empsalary",
            },
        ),
    ]
