# Generated by Django 5.0.7 on 2024-09-23 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "employees",
            "0002_alter_empsalary_adhoc_allowance_alter_empsalary_apfb_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="empbasicinfo",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="empsalary",
            name="created_by",
        ),
    ]
