# Generated by Django 5.0.7 on 2024-09-25 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_remove_employee_created_by_customuser"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CustomUser",
        ),
    ]
